-- заполнение таблицы RATING

MERGE INTO RATING AS target
USING (SELECT 1 AS RATING_ID, 'G' AS RATING_NAME) AS source
ON target.RATING_ID = source.RATING_ID
WHEN MATCHED THEN
    UPDATE SET target.RATING_NAME = source.RATING_NAME
WHEN NOT MATCHED THEN
    INSERT (RATING_ID, RATING_NAME) VALUES (source.RATING_ID, source.RATING_NAME);

MERGE INTO RATING AS target
USING (SELECT 2 AS RATING_ID, 'PG' AS RATING_NAME) AS source
ON target.RATING_ID = source.RATING_ID
WHEN MATCHED THEN
    UPDATE SET target.RATING_NAME = source.RATING_NAME
WHEN NOT MATCHED THEN
    INSERT (RATING_ID, RATING_NAME) VALUES (source.RATING_ID, source.RATING_NAME);

MERGE INTO RATING AS target
USING (SELECT 3 AS RATING_ID, 'PG-13' AS RATING_NAME) AS source
ON target.RATING_ID = source.RATING_ID
WHEN MATCHED THEN
    UPDATE SET target.RATING_NAME = source.RATING_NAME
WHEN NOT MATCHED THEN
    INSERT (RATING_ID, RATING_NAME) VALUES (source.RATING_ID, source.RATING_NAME);

MERGE INTO RATING AS target
USING (SELECT 4 AS RATING_ID, 'R'
AS RATING_NAME) AS source
ON target.RATING_ID = source.RATING_ID
WHEN MATCHED THEN
    UPDATE SET target.RATING_NAME = source.RATING_NAME
WHEN NOT MATCHED THEN
    INSERT (RATING_ID, RATING_NAME) VALUES (source.RATING_ID, source.RATING_NAME);

MERGE INTO RATING AS target
USING (SELECT 5 AS RATING_ID, 'NC' AS RATING_NAME) AS source
ON target.RATING_ID = source.RATING_ID
WHEN MATCHED THEN
    UPDATE SET target.RATING_NAME = source.RATING_NAME
WHEN NOT MATCHED THEN
    INSERT (RATING_ID, RATING_NAME) VALUES (source.RATING_ID, source.RATING_NAME);

-- заполнение таблицы GENRES

MERGE INTO GENRES AS target
USING (SELECT 1 AS GENRE_ID, 'Комедия' AS GENRE_NAME) AS source
ON target.GENRE_ID = source.GENRE_ID
WHEN MATCHED THEN
    UPDATE SET target.GENRE_NAME = source.GENRE_NAME
WHEN NOT MATCHED THEN
    INSERT (GENRE_ID, GENRE_NAME) VALUES (source.GENRE_ID, source.GENRE_NAME);

MERGE INTO GENRES AS target
USING (SELECT 2 AS GENRE_ID, 'Драма' AS GENRE_NAME) AS source
ON target.GENRE_ID = source.GENRE_ID
WHEN MATCHED THEN
    UPDATE SET target.GENRE_NAME = source.GENRE_NAME
WHEN NOT MATCHED THEN
    INSERT (GENRE_ID, GENRE_NAME) VALUES (source.GENRE_ID, source.GENRE_NAME);

MERGE INTO GENRES AS target
USING (SELECT 3 AS GENRE_ID, 'Мультфильм' AS GENRE_NAME) AS source
ON target.GENRE_ID = source.GENRE_ID
WHEN MATCHED THEN
    UPDATE SET target.GENRE_NAME = source.GENRE_NAME
WHEN NOT MATCHED THEN
    INSERT (GENRE_ID, GENRE_NAME) VALUES (source.GENRE_ID, source.GENRE_NAME);

MERGE INTO GENRES AS target
USING (SELECT 4 AS GENRE_ID, 'Триллер' AS GENRE_NAME) AS source
ON target.GENRE_ID = source.GENRE_ID
WHEN MATCHED THEN
    UPDATE SET target.GENRE_NAME = source.GENRE_NAME
WHEN NOT MATCHED THEN
    INSERT (GENRE_ID, GENRE_NAME) VALUES (source.GENRE_ID, source.GENRE_NAME);

MERGE INTO GENRES AS target
USING (SELECT 5 AS GENRE_ID, 'Документальный' AS GENRE_NAME) AS source
ON target.GENRE_ID = source.GENRE_ID
WHEN MATCHED THEN
    UPDATE SET target.GENRE_NAME = source.GENRE_NAME
WHEN NOT MATCHED THEN
    INSERT (GENRE_ID, GENRE_NAME) VALUES (source.GENRE_ID, source.GENRE_NAME);

MERGE INTO GENRES AS target
USING (SELECT 6 AS GENRE_ID, 'Боевик' AS GENRE_NAME) AS source
ON target.GENRE_ID = source.GENRE_ID
WHEN MATCHED THEN
    UPDATE SET target.GENRE_NAME = source.GENRE_NAME
WHEN NOT MATCHED THEN
    INSERT (GENRE_ID, GENRE_NAME) VALUES (source.GENRE_ID, source.GENRE_NAME);
